version: '3'

services:
  memora:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/memora
    depends_on:
      - db
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to start...' &&
        while ! pg_isready -h db -U postgres; do
          echo 'Waiting for PostgreSQL to become available...'
          sleep 2
        done &&
        echo 'PostgreSQL is up - initializing database...' &&
        python -m app.cli db-migrate --init &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=memora
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 